services:

  api:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: prod
    ports:
      - target: 8080
        published: 8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'

  api-dev:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: dev
    volumes:
      - type: bind
        source: ./api
        target: /api
    depends_on:
      - db
    environment:
      PORT: 8081
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
    working_dir: /api
    ports:
      - target: 8081
        published: 8081
    tty: true
    stdin_open: true

  client:
    build:
      context: './client'
      dockerfile: './Dockerfile'
    command: /bin/bash
    tty: true
    stdin_open: true

  db:
    image: postgres:16
    ports:
      - target: 5432
        published: 5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB

  nginx:
    image: nginx:latest
    ports:
      - target: 3000
        published: 3000
    volumes:
      - type: bind
        source: './nginx'
        target: '/etc/nginx/conf.d'
    depends_on:
      - api
    tty: true
    stdin_open: true
