services:
  api:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: prod
    ports:
      - target: 8080
        published: 8080
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
  api-dev:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: dev
    volumes:
      - type: bind
        source: ./api
        target: /api
    working_dir: /api
    ports:
      - target: 8081
        published: 8081
    tty: true
    stdin_open: true
  client:
    build:
      context: './client'
      dockerfile: './Dockerfile'
    command: /bin/bash
    tty: true
    stdin_open: true
