version: '3.9'

services:
  api:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: prod
    ports:
      - target: 8080
        published: 8080
    tty: true
  api-dev:
    build:
      context: './api'
      dockerfile: './Dockerfile'
      target: dev
    volumes:
      - type: bind
        source: ./api
        target: /api
    working_dir: /api
    ports:
      - target: 8080
        published: 8080
    tty: true
    stdin_open: true
